name: Build
on: push
jobs:
  linux_build:
    runs-on: ubuntu-latest
    container: node:18
    steps:

    - name: Get files
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install -g vsce --save
        vsce package

    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./*.vsix
